
SEskills_keywords = [
    "Python",
    "Java",
    "C++",
    "C#",
    "JavaScript",
    "HTML",
    "CSS",
    "SQL",
    "Git",
    "Docker",
    "Kubernetes",
    "RESTful",
    "APIs",
    "AWS",
    "Azure",
    "Google Cloud",
    "Linux",
    "Unix",
    "Shell Scripting",
    "Data Structures",
    "Algorithms",
    "Object-Oriented Programming",
    "Functional Programming",
    "Frontend Development",
    "Backend Development",
    "Web Development",
    "Mobile App Development",
    "Database Design",
    "NoSQL",
    "Microservices",
    "Agile Development",
    "Scrum",
    "Kanban",
    "Continuous Integration",
    "Continuous Deployment",
    "Test-Driven Development",
    "DevOps",
    "Software Architecture",
    "Design Patterns",
    "Code Review",
    "Unit Testing",
    "Debugging",
    "Performance Optimization",
    "User Experience (UX)",
    "User Interface (UI) Design",
    "Version Control",
    "Dependency Management",
    "Agile Methodologies",
    "Software Development Lifecycle",
    "Code Optimization",
    "Scalability",
    "Serverless Computing",
    "CI/CD",
    "AI",
    "Blockchain",
    "IoT",
    "Big Data",
    "Data Science",
    "Software Testing",
    "Automation Testing",
    "Containerization",
    "Scripting",
    "Microsoft Visual Studio",
    "Microsoft .NET framework",
    "UML",
    "ASIC flow layout design",
    "design to tape-out",
    "EDA tools",
    "NLP",
    "BERT",
    "GPT",
    "spaCy",
    "DOTNET",
    "SDLC",
    "GEM",
    "SECS",
    "system design",
    "Knowledge of programming",
    "OOP",
    ".NET",
    "cloud technologies",
    "servo",
    "motion control systems",
    "Unreal Engine",
    "Unity",
    "embedded software development",
    "quality control",
    "node.js"
]

IEskills_keywords = [
    "Cybersecurity",
    "Information Security",
    "Network Security",
    "Security Architecture",
    "Penetration Testing",
    "Vulnerability Assessment",
    "Incident Response",
    "Security Policies",
    "Risk Assessment",
    "Security Auditing",
    "Firewalls",
    "Intrusion Detection System",
    "IDS",
    "Intrusion Prevention System",
    "IPS",
    "Security Awareness",
    "Encryption",
    "Access Control",
    "Security Compliance",
    "Security Protocols",
    "Security Analysis",
    "Security Incident Management",
    "Security Operations",
    "Identity and Access Management",
    "IAM",
    "Information Security Manager",
    "Certified Ethical Hacker",
    "Information Systems Auditor",
    "Cloud Security Professional",
    "Security Tools",
    "Intrusion Detection and Prevention Systems",
    "IDPS",
    "Antivirus Software",
    "Firewall Management",
    "Network Monitoring",
    "Forensic Analysis",
    "Malware Analysis",
    "Data Loss Prevention",
    "DLP",
    "Security Patch Management",
    "Security Awareness Training",
    "Security Risk Management",
    "Secure Coding Practices",
    "Cloud Security",
    "Mobile Device Security",
    "Wireless Network Security",
    "Physical Security",
    "Business Continuity Planning",
    "Disaster Recovery Planning",
    "Security Consulting",
    "Security Governance",
    "Security Metrics and KPIs",
    "Threat Intelligence",
    "Security Awareness Programs",
    "Security Best Practices",
    "Cybersecurity Frameworks",
    "Security Assessment",
    "Security Compliance",
    "Security Strategy",
]

Q_keywords = [
    "Vocational",
    "Bachelor",
    "Master"
    "Doctoral",
    "PhD"
    "Certification",
    "Diploma"
]
